export const styles: Record<string, React.CSSProperties> = {
    body: {
      fontFamily: 'Arial, sans-serif',
      backgroundColor: '#f9f9f9',
      padding: '20px',
    },
    container: {
      backgroundColor: '#ffffff',
      padding: '20px',
      borderRadius: '10px',
      maxWidth: '600px',
      margin: 'auto',
    },
    section: { textAlign: 'center' as 'center', padding: '20px' },
    h1: { fontSize: '24px', fontWeight: 'bold', color: '#333' },
    text: { fontSize: '16px', color: '#666', lineHeight: '1.5' },
    button: {
      backgroundColor: '#007bff',
      color: '#fff',
      padding: '10px 20px',
      textDecoration: 'none',
      borderRadius: '5px',
      display: 'inline-block',
      marginTop: '10px',
    },
    secondaryButton: {
      backgroundColor: '#6c757d',
      color: '#fff',
      padding: '8px 15px',
      textDecoration: 'none',
      borderRadius: '5px',
      display: 'inline-block',
      marginTop: '10px',
    },
    link: { color: '#007bff', textDecoration: 'none' },
    hr: { border: 'none', borderTop: '1px solid #ddd', margin: '20px 0' },
    footer: { textAlign: 'center' as 'center', padding: '10px 0' },
    socialIcons: {
      display: 'flex',
      justifyContent: 'center',
      gap: '10px',
      marginTop: '10px',
    },
  }